server:
  port: 8080

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/moyeorak_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/moyeorak_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    url: jdbc:mysql://goorm-mysql.c92y0sa8e7t2.ap-northeast-2.rds.amazonaws.com:3306/moyeorak_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    ausername: choi
    password: 1q2w3e4r!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  jwt:
    #private-key-path: ${JWT_PRIVATE_KEY_PATH}
    #public-key-path: ${JWT_PUBLIC_KEY_PATHa}
    private-key-path: /opt/auth-service/src/main/resources/keys/private_pkcs8.pem
    public-key-path: /opt/auth-service/src/main/resources/keys/public.pem

