server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moyeorak_auth
    username: root
    password: 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET:my_super_secret_key}
  access-token-validity: 3600000      # 1시간
  refresh-token-validity: 1209600000  # 2주